### PR TITLE
Adding null checks to equals overrides.

### PR DESCRIPTION
**Pull request by DamienLegay**
Signed-off-by: Damien Legay.

### CODE REVIEW

**Comment by tommens** [comment]
Damien, thanks for this pull request. I did not merge it yet, but I will. Related to this pull request, can you also propose unit tests that check for failures if one would try to compare equality with null expressions? There is already a testEquals method for most of the classes, it can either be extended or another similar one can be added. In principle, all of those unit tests would fail in the previous version of the code; and all of those unit tests would succeed in the new version of the code to which you added null checking in the equals methods.

**Comment by tommens** [comment]
@DamienLegay in addition to my previous comment on this PR, something else that is directly related but still missing (it is mentioned as a TO DO in the current code) are the implementations of the hashCode() methods. It is expected to redefine the hashCode() method in an appropriate way whenever the equals() method is redefined.
Also related to my previous comment: without providing unit tests that accompany the pull request, the test coverage of the code will decrease, since an additional condition has been added in the equals() methods, and this adding condition has not yet been covered by the tests. This is another reason for always providing unit tests together with code changes; in an ideal world we do not want to reduce test coverage  when adding new code.

**Comment by DamienLegay** [comment]
> Damien, thanks for this pull request. I did not merge it yet, but I will. Related to this pull request, can you also propose unit tests that check for failures if one would try to compare equality with null expressions? There is already a testEquals method for most of the classes, it can either be extended or another similar one can be added. In principle, all of those unit tests would fail in the previous version of the code; and all of those unit tests would succeed in the new version of the code to which you added null checking in the equals methods.

As-is, the tests would not fail without it, since instanceof() is used, and instanceof() does check for null; but this ties in to the question of using instanceof() vs getClass(): the former will let subclasses pass, the latter will not.
For instance:

```
public class Animal
{
    protected String name; 
    public Animal(String name) {this.name = name;}
    public boolean equals(object o)
    {
         if (o == null) return false; // Not strictly necessary in this version
         if (this == o) return true;
         if (!(o instanceof Animal)) return false;
        return Object.equals(name, (Animal) o.name());
    }
    ...
}
public class Shark extends Animal {...}

public class BehaviourDifferences
{
    public static void main(String[] args)
    {
        Animal a = new Animal("Bruce");
        Shark s = new Shark ("Bruce");
        System.out.println(s.equals(a)); // **true**
    }
}
```

The comparison will return true. Thus, every animal named "Bruce" is a shark (named Bruce).


But in this example:

```
public class Animal
{
    protected String name; 
    public Animal(String name) {this.name = name;}
    public boolean equals(object o)
    {
         if (o == null) return false; // Absolutely necessary, this time
         if (this == o) return true;
         if (this.getClass() != o.getClass()) return false;
        return Object.equals(name, (Animal) o.name());
    }
    ...
}
public class Shark extends Animal {...}

public class BehaviourDifferences
{
    public static void main(String[] args)
    {
        Animal a = new Animal("Bruce");
        Shark s = new Shark ("Bruce");
        System.out.println(s.equals(a)); // **false**
    }
}
```

The comparison will return false. Thus, just because an animal has the same properties (name, here) as another does not necessarily mean they are the same.

So, the usage of instanceof() vs getClass() depends on the nature of the class and its subclasses, and the check against null is only necessary in the latter use (but not harmful in the former, it prevents the instanceof() be later changed to getClass() without remembering to add the check).

Here, the equals() methods are implemented in the subclasses (Plus, Minus, Times, Divides), so it doesn't make a difference... but I'd push them up to Operation(), since they are the same method (thus, repetitive, thus harder to maintain). 
Wanted to check with you before making that change, though, in case it's a deliberate choice to teach students.

**Comment by tommens** [comment]
Performing a push up operation to have the equals() at the level of the Operation class would be cleaner indeed to avoid code duplication. Especially because it would not only be the equals() but also the hashCode() method (not yet implemented but it should) that will be repetitive as well. I do not know what would be the precise impact of this push up, but if nothing else breaks, then I would be in favour of this refactoring, because it will reduce the code size and it will remove code redundancy and hence reduce the risk of bugs. We should apply the practices we preach/teach. You can propose the pull request for this refactoring (after checking locally that everything works), possibly with new added unit tests (or moved unit tests), I will then integrate the changes into the main branch. I prefer working in this way because it will also show the students about how the PR process works in practice. (Otherwise, I would already have given commit access long ago to you and Gauvain.)

**Comment by DamienLegay** [comment]
Ok, will do. I did try to commit directly and was surprised that I didn't have access.

**Comment by tommens** [comment]
So, it was deliberate ;-) I have created an issue for the pull up operation. I will link the issue to the PR that you will propose, this will allow me to show as well how you can link issues to pull requests. In fact, I will assign the issue to you, to also illustrate how to assign issues to people...

**Pull request merged**
